blank_issues_enabled: true
contact_links:
  - name: Questions or Discussions
    url: https://github.com/jaimanm/wildfire-detection/discussions
    about: Ask questions or start discussions about the project
